# syntax=docker/dockerfile:1

ARG RUBY_VERSION=3.4.3
FROM ruby:${RUBY_VERSION}

WORKDIR /app

# Dependências
RUN apt-get update -qq && apt-get install -y \
  build-essential \
  libpq-dev \
  libpq5 \
  git \
  curl \
  && rm -rf /var/lib/apt/lists/*

# Configuração do bundler
ENV BUNDLE_PATH=/usr/local/bundle

# Cache de gems
COPY Gemfile Gemfile.lock ./
RUN bundle install

EXPOSE 3000

CMD ["bash"]